//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHomeBudget.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeBudget3Entities : DbContext
    {
        public HomeBudget3Entities()
            : base("name=HomeBudget3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<Client_subcategories> Client_subcategories { get; set; }
        public virtual DbSet<Client_wallet> Client_wallet { get; set; }
        public virtual DbSet<subcategories> subcategories { get; set; }
        public virtual DbSet<Transact> Transact { get; set; }
        public virtual DbSet<wallet> wallet { get; set; }
    }
}
